[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {workspace=true}
bevy_renet = {workspace=true}
bincode = "1.3.3"
serde = "1.0.152"
common = {path="../common"}
iyes_loopless = "0.9.1"
bevy_rapier3d = "0.20.0"
